### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by tc214** [itsMelo/UDPSocketDemo#1]
楼主：
你好！ 最近刚好在做UDP相关的项目，有一个问题想请教你，DatagramSocket receive 方法放在子线程中，receive方法是阻塞的，如果长时间没有收到消息，系统可能会回收该子线程，如何处理这种情况呢？

**Comment by itsMelo** [comment]
在 Android 线程尽量使用 ThreadPoolExecutor，设置核心线程数，即便是线程空闲，核心线程也不会被回收的。
